# Find all the available rules by running:
# swiftlint rules
#

# rule identifiers to exclude from running
disabled_rules:
    - force_try
    - todo
    - trailing_whitespace
    - type_name
    - large_tuple
    - redundant_optional_initialization
    - empty_parentheses_with_trailing_closure
    - cyclomatic_complexity
    - superfluous_disable_command
    - force_cast
    - unused_closure_parameter
    - weak_delegate
    - operator_whitespace
    - variable_name

    #- vertical_whitespace
    #- function_parameter_count
    #- type_body_length
    #- operator_whitespace
    #- colon
    #- comma
    #- control_statement


# paths to ignore during linting. Takes precedence over `included`.
excluded:
    - Carthage

# configurable rules can be customized from this configuration file
line_length:
    warning: 260
    error: 400
type_body_length:
    warning: 300
    error: 500
function_body_length:
    warning: 100
    error: 150
identifier_name:
    max_length:
        warning: 50
        error: 80
nesting:
    type_level:
        warning: 4
        error: 6
    statement_level:
        warning: 4
        error: 6

